<a href="https://colab.research.google.com/github/abdulsamad00529/ML-assignments-FlyRank-AI/blob/main/w03_data_contract.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-04 — Search Intelligence Data Contract

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/flyrank-bih/flyrank-ml-internship-starter/blob/main/work/notebooks/w03_data_contract.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. Unit of analysis + time window

*One row = one what, over which dates? State it, then verify it below.*

The unit of analysis for this data contract is **[One row represents what? e.g., one user search query]**. The time window for each row is **[Over what period? e.g., daily, hourly, instantaneous]** and the overall dataset covers dates from **[Start Date]** to **[End Date]**.

In [9]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

In [10]:
import pandas as pd

# Placeholder for your data loading. Replace this with your actual data source.
# For example, if you have a CSV file:
# df = pd.read_csv('your_search_intelligence_data.csv')

# Creating a dummy DataFrame for demonstration
data = {
    'query_id': [1, 2, 3, 4, 5],
    'user_id': ['A', 'B', 'A', 'C', 'B'],
    'query_text': ['laptop', 'phone', 'mouse', 'keyboard', 'headphones'],
    'timestamp': pd.to_datetime(['2023-01-01 10:00:00', '2023-01-01 10:05:00', '2023-01-02 11:00:00', '2023-01-02 11:15:00', '2023-01-03 12:00:00'])
}
df = pd.DataFrame(data)

# Display the first few rows to understand the unit of analysis
print("First 5 rows of the DataFrame:")
display(df.head())

# Verify the number of rows (unit of analysis count)
print(f"\nTotal number of rows: {len(df)}")

# Verify the time window. Assuming a 'timestamp' column exists.
if 'timestamp' in df.columns and pd.api.types.is_datetime64_any_dtype(df['timestamp']):
    min_date = df['timestamp'].min()
    max_date = df['timestamp'].max()
    print(f"\nDate range: {min_date} to {max_date}")
else:
    print("\nCould not verify time window: 'timestamp' column not found or not in datetime format.")

# You might also want to check for duplicates based on your unit of analysis.
# For example, if 'query_id' is the unique identifier for a search query:
if 'query_id' in df.columns:
    duplicate_queries = df[df.duplicated(subset=['query_id'], keep=False)]
    if not duplicate_queries.empty:
        print(f"\nFound {len(duplicate_queries)} duplicate query_ids. Here are some examples:\n")
        display(duplicate_queries)
    else:
        print("\nNo duplicate 'query_id' found.")

First 5 rows of the DataFrame:

   query_id user_id  query_text           timestamp
0         1       A      laptop 2023-01-01 10:00:00
1         2       B       phone 2023-01-01 10:05:00
2         3       A       mouse 2023-01-02 11:00:00
3         4       C    keyboard 2023-01-02 11:15:00
4         5       B  headphones 2023-01-03 12:00:00

Total number of rows: 5

Date range: 2023-01-01 10:00:00 to 2023-01-03 12:00:00

No duplicate 'query_id' found.

## 2. Fields: feature / label / context / excluded

*Sort every field you plan to touch into these four buckets. Excluded needs a why.*

In [11]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

print("Current columns in your DataFrame:")
print(df.columns.tolist())

# \u25BC \u25BC \u25BC Fill in your categorizations below \u25BC \u25BC \u25BC

# Example categories (replace with your actual field names and their classifications):
features = ['query_text']
labels = [] # e.g., ['relevance_score']
context = ['query_id', 'user_id', 'timestamp']
excluded = [] # e.g., ['raw_log_entry']

# \u25B2 \u25B2 \u25B2 Fill in your categorizations above \u25B2 \u25B2 \u25B2

all_categorized_fields = set(features + labels + context + excluded)
all_dataframe_columns = set(df.columns.tolist())

print(f"\nTotal columns in DataFrame: {len(all_dataframe_columns)}")
print(f"Total fields categorized: {len(all_categorized_fields)}")

# Check if all DataFrame columns are categorized
uncategorized_columns = all_dataframe_columns - all_categorized_fields
if uncategorized_columns:
    print(f"\nWARNING: The following columns are in the DataFrame but are NOT categorized: {list(uncategorized_columns)}")
else:
    print("\nAll DataFrame columns have been categorized.")

# Check for categorized fields not present in the DataFrame (e.g., typos)
misplaced_categorized_fields = all_categorized_fields - all_dataframe_columns
if misplaced_categorized_fields:
    print(f"\nWARNING: The following categorized fields are NOT in the DataFrame: {list(misplaced_categorized_fields)}")

# Display sample data for each category (if available)
print("\n--- Sample Data by Category ---")
if features:
    print("\nFeatures (first 5 rows):\n")
    display(df[features].head())
if labels:
    print("\nLabels (first 5 rows):\n")
    display(df[labels].head())
if context:
    print("\nContext (first 5 rows):\n")
    display(df[context].head())
if excluded:
    print("\nExcluded fields are not typically displayed, as they are removed from consideration.\n")

Current columns in your DataFrame:
['query_id', 'user_id', 'query_text', 'timestamp']

Total columns in DataFrame: 4
Total fields categorized: 4

All DataFrame columns have been categorized.

--- Sample Data by Category ---

Features (first 5 rows):

   query_text
0      laptop
1       phone
2       mouse
3    keyboard
4  headphones

Context (first 5 rows):

   query_id user_id           timestamp
0         1       A 2023-01-01 10:00:00
1         2       B 2023-01-01 10:05:00
2         3       A 2023-01-02 11:00:00
3         4       C 2023-01-02 11:15:00
4         5       B 2023-01-03 12:00:00

## 3. Verify it with queries (grain, counts, missing values, windows)

*Every claim above gets a query cell here. A contract claim without a query next to it is a guess.*

Here I claim that...

*   **Claim 1 (Grain):** [E.g., Each row represents a unique user search query, identified by `query_id`.]
*   **Claim 2 (Counts):** [E.g., There are no missing values in the `query_text` column.]
*   **Claim 3 (Time Window):** [E.g., The `timestamp` column contains data for every day within the specified range, without gaps.]
*   **Claim 4 (Missing Values):** [E.g., The `user_id` column has no more than 5% missing values.]

In [12]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

print("--- Verification Queries ---")

# Query 1: Verify Claim 1 (Grain - uniqueness of query_id)
if 'query_id' in df.columns:
    is_query_id_unique = df['query_id'].is_unique
    print(f"\nVerification of Claim 1 (Grain - `query_id` uniqueness): {is_query_id_unique}")
    if not is_query_id_unique:
        print("WARNING: `query_id` is not unique. Here are some duplicates:")
        display(df[df.duplicated(subset=['query_id'], keep=False)])
else:
    print("\n`query_id` column not found for Claim 1 verification.")

# Query 2: Verify Claim 2 (Counts - missing values in query_text)
if 'query_text' in df.columns:
    missing_query_text = df['query_text'].isnull().sum()
    print(f"\nVerification of Claim 2 (Missing values in `query_text`): {missing_query_text} missing values.")
    if missing_query_text > 0:
        print("WARNING: Missing values found in `query_text`.")
else:
    print("\n`query_text` column not found for Claim 2 verification.")

# Query 3: Verify Claim 3 (Time Window - completeness, e.g., no gaps for daily data)
# This is a more complex check and depends on the expected granularity (e.g., daily, hourly).
# For simplicity, let's check if the date range covers the expected period.
if 'timestamp' in df.columns and pd.api.types.is_datetime64_any_dtype(df['timestamp']):
    min_ts = df['timestamp'].min()
    max_ts = df['timestamp'].max()
    print(f"\nVerification of Claim 3 (Time Window - overall range): Data spans from {min_ts.date()} to {max_ts.date()}.")
    # Further checks like daily gaps would require defining an expected date range and checking for missing dates
    # For instance, if expecting daily data without gaps:
    # expected_dates = pd.date_range(start=min_ts.date(), end=max_ts.date(), freq='D')
    # actual_dates = df['timestamp'].dt.normalize().unique()
    # missing_dates = set(expected_dates) - set(actual_dates)
    # if missing_dates:
    #     print(f"WARNING: Missing dates in `timestamp` column: {sorted(list(missing_dates))}")
else:
    print("\n`timestamp` column not found or not in datetime format for Claim 3 verification.")

# Query 4: Verify Claim 4 (Missing Values - user_id has less than 5% missing)
if 'user_id' in df.columns:
    total_rows = len(df)
    missing_user_id = df['user_id'].isnull().sum()
    missing_percentage = (missing_user_id / total_rows) * 100 if total_rows > 0 else 0
    print(f"\nVerification of Claim 4 (Missing values in `user_id`): {missing_user_id} missing values ({missing_percentage:.2f}%).")
    if missing_percentage > 5:
        print("WARNING: More than 5% missing values found in `user_id`.")
else:
    print("\n`user_id` column not found for Claim 4 verification.")

--- Verification Queries ---

Verification of Claim 1 (Grain - `query_id` uniqueness): True

Verification of Claim 2 (Missing values in `query_text`): 0 missing values.

Verification of Claim 3 (Time Window - overall range): Data spans from 2023-01-01 to 2023-01-03.

Verification of Claim 4 (Missing values in `user_id`): 0 missing values (0.00%).

Here are the inherent limitations of this data:

*   **Limitation 1 (Example):** This data only includes searches from registered users, so it cannot tell us about guest user behavior.
*   **Limitation 2 (Example):** The time window only covers recent data, so it cannot tell us about long-term trends or seasonal patterns beyond this period.
*   **Limitation 3 (Example):** [Add another limitation specific to your data, e.g., missing specific event types, aggregation level issues, etc.]

## 4. Data limits

*What can this data never tell you? Unbalanced history, GSC-only early rows, window overlaps.*

## 5. Proposed metric(s)

*What metric will come from this data? How exactly is it defined, what are its properties?*

Here are the proposed metrics derived from this data:

*   **Metric 1 (Example):** Click-Through Rate (CTR) - Defined as (Number of Clicks / Number of Impressions) * 100. It measures the percentage of times a search result was clicked after being displayed. Properties: Varies between 0 and 100, higher is generally better, sensitive to result ordering and query intent.
*   **Metric 2 (Example):** [Add another metric, e.g., Session Duration, Conversion Rate, Query Refinement Rate.]

In [13]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

print("--- Metric Calculations ---")

# Example: To calculate a dummy CTR, you'd need click and impression data.
# Let's add dummy 'impressions' and 'clicks' to our DataFrame for demonstration.
import numpy as np

if 'impressions' not in df.columns:
    df['impressions'] = np.random.randint(1, 10, size=len(df)) # Random impressions between 1 and 9
if 'clicks' not in df.columns:
    df['clicks'] = df['impressions'].apply(lambda x: np.random.randint(0, x + 1)) # Clicks <= impressions

print("DataFrame with dummy impressions and clicks:")
display(df.head())

# Metric 1: Calculate Click-Through Rate (CTR) per query
df['ctr'] = (df['clicks'] / df['impressions'] * 100).fillna(0)

print("\nCTR per query:")
display(df[['query_id', 'impressions', 'clicks', 'ctr']].head())

# You might want to calculate an overall CTR or other aggregates
overall_impressions = df['impressions'].sum()
overall_clicks = df['clicks'].sum()
overall_ctr = (overall_clicks / overall_impressions * 100) if overall_impressions > 0 else 0
print(f"\nOverall CTR: {overall_ctr:.2f}%")

# Metric 2: Placeholder for your second metric calculation
# For example, if you define 'Session Duration', you would need columns like 'session_start_time' and 'session_end_time'.
# df['session_duration_minutes'] = (df['session_end_time'] - df['session_start_time']).dt.total_seconds() / 60
# print(f"\nAverage Session Duration: {df['session_duration_minutes'].mean():.2f} minutes")

--- Metric Calculations ---
DataFrame with dummy impressions and clicks:

   query_id user_id  query_text           timestamp  impressions  clicks
0         1       A      laptop 2023-01-01 10:00:00            7       5
1         2       B       phone 2023-01-01 10:05:00            5       1
2         3       A       mouse 2023-01-02 11:00:00            6       0
3         4       C    keyboard 2023-01-02 11:15:00            5       3
4         5       B  headphones 2023-01-03 12:00:00            2       2

CTR per query:

   query_id  impressions  clicks         ctr
0         1            7       5   71.428571
1         2            5       1   20.000000
2         3            6       0    0.000000
3         4            5       3   60.000000
4         5            2       2  100.000000

Overall CTR: 44.00%

In [14]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

print("This section is primarily for conceptual limitations. You can add code here to illustrate or quantify some of these limitations if possible.")

# Example: If you claimed data only covers registered users, you might check for nulls or a specific value in a 'user_type' column if it existed.
# if 'user_type' in df.columns:
#     registered_users_count = df[df['user_type'] == 'registered'].shape[0]
#     total_users_count = df.shape[0]
#     print(f"\nPercentage of registered users: {registered_users_count / total_users_count * 100:.2f}%")

# For now, we'll just acknowledge the conceptual nature of this section.

This section is primarily for conceptual limitations. You can add code here to illustrate or quantify some of these limitations if possible.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.